###
GET https://puhelinluettelo-backend-test.onrender.com/api/persons

###
POST https://puhelinluettelo-backend-test.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Jenna Arino",
  "number": "0405412241"
}

###
POST https://puhelinluettelo-backend-test.onrender.com/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "0405412241"
}
###
POST https://puhelinluettelo-backend-test.onrender.com/api/persons
Content-Type: application/json

{
  "name": "aertlhgajegt",
  "number": ""
}
###
POST https://puhelinluettelo-backend-test.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Testi Testi",
  "number": "123123"
}