###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jenna Arino",
  "number": "0405412241"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "0405412241"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "aertlhgajegt",
  "number": ""
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Valtteri Arino",
  "number": ""
}